# Generated by Django 6.0.6 on 2026-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
